### ISSUE TITLE
Changing site settings via Netlify CMS breaks config.yml

### ISSUE THREAD

**Issue by nicholashu** [Cecilapp/starter-blog#50]
If you change the site settings via the Netlify CMS the virtual page config is removed. This makes the pages no longer accessible

```
virtualpages:
  admin:
    layout: admin/index
    output: html
    title: "Content Manager (Netlify CMS)"
  home:
      redirect: /
    _redirects:
    output: netlify_redirects
```
